name: Deploy to Firebase Hosting (Token Method)

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy via Firebase Token
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_TOKEN }}
